<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="E5470-01381" name="Test.ApplicationTest" tests="3" failures="1" timestamp="26 Apr 2018 20:15:11 GMT" time="0.020" errors="0">
  <testcase name="doLogin" time="0.011" classname="Test.ApplicationTest"/>
  <testcase name="AccessDashboard" time="0.005" classname="Test.ApplicationTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Abhay] but found [Abhinav]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Abhay] but found [Abhinav]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at Test.ApplicationTest.AccessDashboard(ApplicationTest.java:53)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- AccessDashboard -->
  <testcase name="logout" time="0.004" classname="Test.ApplicationTest"/>
</testsuite> <!-- Test.ApplicationTest -->
