<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="E5470-01381" ignored="0" name="ApplicationTest" tests="3" failures="1" timestamp="26 Apr 2018 20:15:11 GMT" time="0.087" errors="0">
  <testcase name="doLogin" time="0.006" classname="Test.ApplicationTest"/>
  <testcase name="AccessDashboard" time="0.004" classname="Test.ApplicationTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Abhay] but found [Abhinav]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Abhay] but found [Abhinav]
at Test.ApplicationTest.AccessDashboard(ApplicationTest.java:53)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- AccessDashboard -->
  <testcase name="logout" time="0.001" classname="Test.ApplicationTest"/>
</testsuite> <!-- ApplicationTest -->
