<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="E5470-01381" ignored="0" name="LoginTest" tests="1" failures="1" timestamp="13 Apr 2018 23:07:43 GMT" time="0.035" errors="0">
  <testcase name="LoginTest" time="0.009" classname="testng_listeners.LoginTest">
    <failure type="java.lang.AssertionError" message="expected [B] but found [A]">
      <![CDATA[java.lang.AssertionError: expected [B] but found [A]
at testng_listeners.LoginTest.LoginTest(LoginTest.java:10)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- LoginTest -->
</testsuite> <!-- LoginTest -->
